---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MoTang.
--- DateTime: 30/9/2025 下午 3:14
---

-- 比较线程标识与锁中的标识是否一致
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0